// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char THING_ID[] = "17055640-a912-42a7-a283-86ce11f7d627";
const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRepsChange();

int reps;
int lightMode;
float pctGreen;
float armVertical;

void initProperties();


WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
